# -*- coding: utf-8 -*-
"""BSEF23A020-ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjwqDqdbnD27sfdYXFTiU1P18j1Sy5sT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("real_estate_price_size.csv")
df.head()

print(df.info())
print(df.isnull().sum())

feature = df["size"].to_numpy()
target = df["price"].to_numpy()

mean_size = np.mean(feature)
std_size = np.std(feature)

feature_scaled = (feature - mean_size) / std_size

np.random.seed(42)

indices = np.random.permutation(len(feature_scaled))

train_size = int(0.8 * len(indices))

train_idx = indices[:train_size]
test_idx = indices[train_size:]

X_train = feature_scaled[train_idx]
y_train = target[train_idx]

X_test = feature_scaled[test_idx]
y_test = target[test_idx]

def predict(x, weight, bias):
    return weight * x + bias

def mse_loss(x, y, weight, bias):
    predictions = predict(x, weight, bias)
    error = predictions - y
    return np.mean(error ** 2)

def train_model(x, y, lr=0.01, epochs=1000):

    weight = 0
    bias = 0

    n = len(y)
    cost_history = []

    for epoch in range(epochs):

        predictions = predict(x, weight, bias)

        dw = (2/n) * np.sum((predictions - y) * x)
        db = (2/n) * np.sum(predictions - y)

        weight = weight - lr * dw
        bias = bias - lr * db

        cost = mse_loss(x, y, weight, bias)
        cost_history.append(cost)

    return weight, bias, cost_history

W, B, losses = train_model(X_train, y_train, lr=0.01, epochs=1000)

print("Optimal Weight:", W)
print("Optimal Bias:", B)
print("Final Training Loss:", losses[-1])

test_predictions = predict(X_test, W, B)

plt.figure(figsize=(8,6))

plt.scatter(X_test, y_test, alpha=0.7, label="Actual")
plt.plot(X_test, test_predictions, linestyle="--", label="Predicted")

plt.xlabel("House Size (Scaled)")
plt.ylabel("House Price")
plt.title("Linear Regression Result")
plt.legend()
plt.grid(True)

plt.show()